azs:
- name: z1
  cloud_properties: {availability_zone: us-east-1a}

vm_types:
- name: default
  cloud_properties:
    instance_type: t2.micro
    ephemeral_disk: {size: 3000, type: gp2}
- name: medium
  cloud_properties:
    instance_type: m3.medium
    ephemeral_disk: {size: 30000, type: gp2}
- name: large
  cloud_properties:
    instance_type: m3.large
    ephemeral_disk: {size: 30000, type: gp2}

vm_extensions:
- name: concourse-disk
  disk_size: 50_000
  cloud_properties:
    type: gp2
- name: concourse-elb
  cloud_properties:
    elbs: [concourse-elb] #This should be the name of the ELB in AWS

disk_types:
- name: default
  disk_size: 3000
  cloud_properties: {type: gp2}
- name: large
  disk_size: 50_000
  cloud_properties: {type: gp2}

networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    az: z1
    static: [10.0.0.62]
    dns: [10.0.0.2]
    reserved: [10.0.0.2-10.0.0.5]
    cloud_properties:
      subnet: #CHANGE_ME
      security_groups: [concourse-vm] #this should be the name of security group in AWS
- name: vip
  type: vip

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: z1
  vm_type: large
  network: default
